# Generated by Django 3.0.7 on 2020-06-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlist',
            options={'verbose_name_plural': 'Waitlist'},
        ),
    ]
